import { ClerkProvider } from "@clerk/nextjs";
import "../../styles/global.css";
import AppLogo from "@/components/layout/logo";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-slate-100 sm:p-7 p-3 min-h-screen">
      <div className="flex mb-10">
        <AppLogo />
      </div>
      {children}
    </div>
  );
}
