"use client";

import BuildSurveyNavigation from "@/components/survey/build-survey-navigation";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BuildSurveyLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div>
        <h1 className="text-2xl font-bold py-4">
          This is the title of survey/quiz
        </h1>
      </div>
      <BuildSurveyNavigation />
      {children}
    </>
  );
}
